import type { Generator } from "../core/generator.js";
import { PackageManager } from "../core/package-manager.js";
import { Result } from "../core/result.js";
import { generationFailure, writeProjectFile } from "./shared.js";

function stackLines(context: Parameters<Generator["generate"]>[0]): readonly string[] {
  const lines: string[] = [];
  for (const client of context.config.clients) lines.push(`- Client: ${client.kind}`);
  if (context.config.backend.kind !== "none") {
    lines.push(`- Backend: ${context.config.backend.kind} + ${context.config.backend.framework}`);
  }
  if (context.config.database.kind !== "none") {
    lines.push(`- Database: ${context.config.database.kind} + ${context.config.database.dataLayer}`);
  }
  lines.push(`- JavaScript workspace: ${context.config.packageManager}`);
  if (context.config.backend.kind === "rust" || context.config.clients.some((client) => client.kind === "tauri")) lines.push("- Rust workspace: Cargo");
  if (context.config.orchestrator === "moon") lines.push("- Orchestrator: Moon");
  if (context.config.docker) lines.push("- Infrastructure: Docker Compose");
  if (context.config.githubActions) lines.push("- CI: GitHub Actions");
  return lines;
}

export const readmeGenerator: Generator = {
  id: "readme",
  label: "README",
  dependencies: ["root"],
  async generate(context) {
    try {
      const runDevelopment = PackageManager.runScript(context.config.packageManager, "dev");
      const runBuild = PackageManager.runScript(context.config.packageManager, "build");
      const install = context.config.install ? "" : `${context.config.packageManager} install\n`;
      await writeProjectFile(
        context,
        "README.md",
        `# ${context.config.projectName}\n\nGenerated by [turks](https://github.com/DeepanshuMishraa/turks).\n\n## Stack\n\n${stackLines(context).join("\n")}\n\n## Start development\n\n\`\`\`bash\ncp .env.example .env\n${context.config.docker ? "docker compose up -d\n" : ""}${install}${runDevelopment}\n\`\`\`\n\n## Useful commands\n\n- \`${runDevelopment}\` — start applications\n- \`${runBuild}\` — build the workspace\n${context.config.docker ? "- `docker compose down` — stop local services\n" : ""}`,
      );
      return Result.ok(undefined);
    } catch (error) {
      return generationFailure("readme", error);
    }
  },
};
